const { SlashCommandBuilder } = require("@discordjs/builders");
const { MessageActionRow, MessageButton, MessageEmbed } = require("discord.js");
module.exports = {
  data: new SlashCommandBuilder()
    .setName("sentiment")
    .setDescription("Learn wether you are being rude, nice or neutral.")
    .addStringOption((option) =>
      option
        .setName("sentence")
        .setDescription(
          "Enter a sentence to be analyzed. (eg. You are very good!)"
        )
        .setRequired(true)
    ),
  async execute(interaction) {
    const phrase = interaction.options.getString("sentence");

    const words = phrase.split(" ");
    if (words.length >= 30) {
      await interaction.editReply({
        content: "Please enter a phrase with less than or equal to 30 words.",
        ephemeral: true,
      });
      return;
    }

    const result = await interaction.client.deepai.callStandardApi(
      "sentiment-analysis",
      {
        text: phrase,
      }
    );

    console.log(result);
    const neutral =
      "http://cdn.shopify.com/s/files/1/1061/1924/products/Neutral_Face_Emoji_grande.png?v=1571606037";
    const positive =
      "https://cdn.shopify.com/s/files/1/1061/1924/products/Smiling_Face_Emoji_large.png?v=1571606036";
    const negative =
      "https://cdn.shopify.com/s/files/1/1061/1924/products/Sad_Face_Emoji_large.png?v=1571606037";

    let img;
    let color;

    if (result["output"].toString().toLowerCase() == "neutral") {
      img = neutral;
      color = "GRAY";
    } else if (
      result["output"].toString().toLowerCase() == "negative" ||
      result["output"].toString().toLowerCase() == "verynegative"
    ) {
      img = negative;
      color = "RED";
    } else if (
      result["output"].toString().toLowerCase() == "positive" ||
      result["output"].toString().toLowerCase() == "verypositive"
    ) {
      img = positive;
      color = "GREEN";
    }

    let sentiment;
    if (result["output"].toString().toLowerCase() == "verypositive") {
      sentiment = "Very Positive";
    } else if (result["output"].toString().toLowerCase() == "verynegative") {
      sentiment = "Very negative";
    } else {
      sentiment = result["output"];
    }

    const embed = new MessageEmbed()
      .setTitle("Sentiment Analysis")
      .setImage(img)

      .addField("Sentence", phrase)
      .addField("Sentiment", `${sentiment}`)
      .setColor(color)
      .setAuthor({
        name: interaction.user.username,
        iconURL: interaction.user.avatarURL(),
      })
      .setFooter({ text: `Generated by ${interaction.user.username}` });

    await interaction.editReply({
      embeds: [embed],
      ephemeral: true,
    });
  },
};
